### ISSUE TITLE
Seperate Middleware should be made for FoodItem pictures (Read Description)

### ISSUE THREAD

**Issue by HamzaTatheer** [HamzaTatheer/SoftwareEngineeringProject#12]
const upload = require("../middleware/multer")("public/uploads/profile_pictures/");

This line made upload download pictures inside a specific folder. We dont want the food pictures going in the same folder
and being called avatar123123.jpeg

instead we want to create a different folder and item being stored as food123123.jpeg

Before you can do that, you need to expose folder as public. This is already done for pfp in config/publicFolders edit it to add foodItems and public folder location

**Comment by fla-t** [comment]
done.
